package com.climb.api.model;

public enum PermissaoCodigo {
    CONTRATO_VISUALIZACAO,
    CONTRATO_CRIACAO,
    CONTRATO_EDICAO,
    CONTRATO_EXCLUSAO,
    CARGO_VISUALIZACAO,
    CARGO_CRIACAO,
    CARGO_EDICAO,
    CARGO_EXCLUSAO,
    DOCUMENTO_JURIDICO_VISUALIZACAO,
    DOCUMENTO_JURIDICO_CRIACAO,
    DOCUMENTO_JURIDICO_EDICAO,
    DOCUMENTO_JURIDICO_EXCLUSAO,
    RELATORIO_VISUALIZACAO,
    RELATORIO_CRIACAO,
    RELATORIO_EDICAO,
    RELATORIO_EXCLUSAO,
    CONTRATO_NIVEL_COMPLEXIDADE,
    PLANILHA_EDICAO_RESTRITA,
    REUNIAO_AGENDAMENTO,
    ARQUIVO_UPLOAD,
    ARQUIVO_DOWNLOAD
}
