package com.climb.api.model;

public enum PermissaoCodigo {
    CONTRATO_CRUD,
    CARGO_CRUD,
    DOCUMENTO_JURIDICO_CRUD,
    CONTRATO_NIVEL_COMPLEXIDADE,
    PLANILHA_EDICAO_RESTRITA,
    REUNIAO_AGENDAMENTO,
    RELATORIO_CRUD,
    ARQUIVO_UPLOAD,
    ARQUIVO_DOWNLOAD
}
