UPDATE propostas
SET status = 'PENDENTE'
WHERE status IS NULL
   OR status NOT IN ('PENDENTE','APROVADA','REJEITADA');

ALTER TABLE propostas
MODIFY COLUMN status ENUM('PENDENTE','APROVADA','REJEITADA')
NOT NULL DEFAULT 'PENDENTE';
